package com.model;

//Generated Jan 1, 2019 3:35:28 PM by Hibernate Tools 5.2.10.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
/**
* Student generated by hbm2java
*/
@Entity
@Table(name = "product", catalog = "flipkart")
public class Product implements java.io.Serializable {

	private static final long serialVersionUID = -6991563062956125351L;
	private Integer productId;
	private String productName;

	public Product() {
	}

	public Product(Integer productId, String productName) {
		this.productId = productId;
		this.productName = productName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PRODUCT_ID", unique = true, nullable = false)
	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	@Column(name = "PRODUCT_NAME", length = 128)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}
}
